Repository equinor/witsml-explorer, pull requests merged in 2021-04, with the labels that each got.

#300 Dockerfiles hadolint and eslint
  Dockerfile-api
  Dockerfile-frontend
Labels: bug

#327 Fix show on server being enabled when no log item is checked
  Src/WitsmlExplorer.Frontend/components/ContextMenus/LogObjectContextMenu.tsx
Labels: bug

#325 Filter on well limit and add filter tests
  Src/WitsmlExplorer.Frontend/components/Sidebar/FilterPanel.tsx
  Src/WitsmlExplorer.Frontend/contexts/__tests__/filter.test.tsx
  Src/WitsmlExplorer.Frontend/contexts/filter.tsx
Labels: enhancement

#331 Change Sidebar items to use server list from context directly instead of passing argument
  Src/WitsmlExplorer.Frontend/components/Sidebar/LogItem.tsx
  Src/WitsmlExplorer.Frontend/components/Sidebar/WellItem.tsx
  Src/WitsmlExplorer.Frontend/components/Sidebar/WellboreItem.tsx
Labels: enhancement

#333 Remove unnecessary variable and fix camel casing
  Src/WitsmlExplorer.Frontend/contexts/__tests__/operationStateReducer.test.tsx
  Src/WitsmlExplorer.Frontend/contexts/operationStateReducer.tsx
Labels: enhancement

#332 Extract duplicate code into ModalParts and fix spelling in WellborePropertiesModal
  Src/WitsmlExplorer.Frontend/components/ContextMenus/LogObjectContextMenu.tsx
  Src/WitsmlExplorer.Frontend/components/ContextMenus/LogsContextMenu.tsx
  Src/WitsmlExplorer.Frontend/components/ContextMenus/WellContextMenu.tsx
  Src/WitsmlExplorer.Frontend/components/ContextMenus/WellboreContextMenu.tsx
  Src/WitsmlExplorer.Frontend/components/Modals/LogPropertiesModal.tsx
  Src/WitsmlExplorer.Frontend/components/Modals/ModalParts.tsx
  Src/WitsmlExplorer.Frontend/components/Modals/ModalPresenter.tsx
  Src/WitsmlExplorer.Frontend/components/Modals/WellPropertiesModal.tsx
  Src/WitsmlExplorer.Frontend/components/Modals/WellborePropertiesModal.tsx
Labels: enhancement

#340 Fix pull request template heading
  .github/pull_request_template.md
Labels: documentation

#347 Fix login dialog not appearing when selecting a server which is already selected
  Src/WitsmlExplorer.Frontend/components/Sidebar/ServerManager.tsx
Labels: bug

#338 backend changes for batch update of well properties
  Src/WitsmlExplorer.Api/Jobs/BatchModifyWellJob.cs
  Src/WitsmlExplorer.Api/Models/JobType.cs
  Src/WitsmlExplorer.Api/Models/RefreshAction.cs
  Src/WitsmlExplorer.Api/Services/JobService.cs
  Src/WitsmlExplorer.Api/Workers/BatchModifyWellWorker.cs
  Src/WitsmlExplorer.Api/Workers/ModifyWellWorker.cs
  Tests/WitsmlExplorer.Api.Tests/Workers/BatchModifyWellWorkerTests.cs
Labels: enhancement
