Repository equinor/witsml-explorer, pull requests merged in 2021-06, with the labels that each got.

#376 When the user tries to open more than 200 mnemonics the request fails
  Src/WitsmlExplorer.Api/Routes.cs
  Src/WitsmlExplorer.Frontend/components/ContentViews/CurveValuesView.tsx
  Src/WitsmlExplorer.Frontend/services/logObjectService.tsx
Labels: bug

#409 Sorting is wrong in some places
  Src/WitsmlExplorer.Frontend/components/ContentViews/CurveValuesView.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/ContentTable.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/VirtualizedContentTable.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/tableParts.ts
Labels: bug

#455 Add Pull request review checklist
  PR_REVIEW_CHECKLIST.md
Labels: documentation

#448 Add support for WitsmlTubular
  Src/Witsml/Data/WitsmlTubular.cs
  Src/Witsml/Data/WitsmlTubularComponent.cs
  Src/Witsml/Data/WitsmlTubulars.cs
  Src/Witsml/Data/WitsmlWellbore.cs
  Src/WitsmlExplorer.Console/ListCommands/ListTubularsCommand.cs
  Src/WitsmlExplorer.Console/Program.cs
  Src/WitsmlExplorer.Console/ShowCommands/ShowTubularCommand.cs
Labels: enhancement

#460 Remove usage of LogQueries in Console application
  Src/WitsmlExplorer.Console/ListCommands/ListLogsCommand.cs
Labels: enhancement

#461 Add checkbox to hide inactive curves
  Src/WitsmlExplorer.Frontend/components/ContentViews/LogCurveInfoListView.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/ContentTable.tsx
  Src/WitsmlExplorer.Frontend/components/Sidebar/FilterPanel.tsx
  Src/WitsmlExplorer.Frontend/contexts/curveThreshold.tsx
Labels: enhancement

#466 Ignore Console package in .prettierignore
  .prettierignore
Labels: enhancement

#463 MessageObject support in `Witsml`
  Src/Witsml/Data/WitsmlMessage.cs
  Src/Witsml/Data/WitsmlMessages.cs
  Src/Witsml/Data/WitsmlObjectReference.cs
Labels: enhancement

#464 MessageObject support in `WitsmlExplorer.Api`
  Src/Witsml/Data/WitsmlObjectReference.cs
  Src/WitsmlExplorer.Api/Jobs/Common/MessageObjectReference.cs
  Src/WitsmlExplorer.Api/Jobs/CreateMessageObjectJob.cs
  Src/WitsmlExplorer.Api/Models/JobType.cs
  Src/WitsmlExplorer.Api/Models/MessageObject.cs
  Src/WitsmlExplorer.Api/Routes.cs
  Src/WitsmlExplorer.Api/Services/JobService.cs
  Src/WitsmlExplorer.Api/Services/MessageObjectService.cs
  Src/WitsmlExplorer.Api/Workers/CreateMessageWorker.cs
  Tests/WitsmlExplorer.IntegrationTests/Api/Services/MessageObjectTests.cs
Labels: enhancement

#472 Moved 'Query' folder from Witsml project to WitsmlExplorer.Api
  Src/Witsml/Query/WellQueries.cs
  Src/WitsmlExplorer.Api/Query/LogQueries.cs
  Src/WitsmlExplorer.Api/Query/RigQueries.cs
  Src/WitsmlExplorer.Api/Query/RiskQueries.cs
  Src/WitsmlExplorer.Api/Query/TrajectoryQueries.cs
  Src/WitsmlExplorer.Api/Query/WellQueries.cs
  Src/WitsmlExplorer.Api/Query/WellboreQueries.cs
  Src/WitsmlExplorer.Api/Services/LogObjectService.cs
  Src/WitsmlExplorer.Api/Services/RigService.cs
  Src/WitsmlExplorer.Api/Services/TrajectoryService.cs
  Src/WitsmlExplorer.Api/Services/WellService.cs
  Src/WitsmlExplorer.Api/Services/WellboreService.cs
  Src/WitsmlExplorer.Api/Workers/BatchModifyWellWorker.cs
  Src/WitsmlExplorer.Api/Workers/CopyLogDataWorker.cs
  Src/WitsmlExplorer.Api/Workers/CopyLogWorker.cs
  Src/WitsmlExplorer.Api/Workers/CopyTrajectoryWorker.cs
  Src/WitsmlExplorer.Api/Workers/CreateLogWorker.cs
  Src/WitsmlExplorer.Api/Workers/CreateMessageWorker.cs
  Src/WitsmlExplorer.Api/Workers/CreateWellWorker.cs
  Src/WitsmlExplorer.Api/Workers/CreateWellboreWorker.cs
  Src/WitsmlExplorer.Api/Workers/DeleteCurveValuesWorker.cs
  Src/WitsmlExplorer.Api/Workers/DeleteMnemonicsWorker.cs
  Src/WitsmlExplorer.Api/Workers/DeleteTrajectoryWorker.cs
  Src/WitsmlExplorer.Api/Workers/DeleteWellWorker.cs
  Src/WitsmlExplorer.Api/Workers/DeleteWellboreWorker.cs
  Src/WitsmlExplorer.Api/Workers/ModifyLogObjectWorker.cs
  Src/WitsmlExplorer.Api/Workers/ModifyWellWorker.cs
  Src/WitsmlExplorer.Api/Workers/ModifyWellboreWorker.cs
  Src/WitsmlExplorer.Api/Workers/RenameMnemonicWorker.cs
  Src/WitsmlExplorer.Api/Workers/TrimLogObjectWorker.cs
  Tests/WitsmlExplorer.IntegrationTests/Api/Workers/CopyLogWorkerTests.cs
  Tests/WitsmlExplorer.IntegrationTests/Witsml/AddToStore/LogObjectTests.cs
  Tests/WitsmlExplorer.IntegrationTests/Witsml/AddToStore/TrajectoryTests.cs
Labels: enhancement

#505 refactor queries for wellbore, data objects
  Src/WitsmlExplorer.Api/Query/LogQueries.cs
  Src/WitsmlExplorer.Api/Query/MessageQueries.cs
  Src/WitsmlExplorer.Api/Query/RigQueries.cs
  Src/WitsmlExplorer.Api/Query/RiskQueries.cs
  Src/WitsmlExplorer.Api/Query/TrajectoryQueries.cs
  Src/WitsmlExplorer.Api/Query/WellboreQueries.cs
  Src/WitsmlExplorer.Api/Services/LogObjectService.cs
  Src/WitsmlExplorer.Api/Services/MessageObjectService.cs
  Src/WitsmlExplorer.Api/Services/RigService.cs
  Src/WitsmlExplorer.Api/Services/TrajectoryService.cs
  Src/WitsmlExplorer.Api/Services/WellboreService.cs
  Src/WitsmlExplorer.Api/Workers/CopyLogDataWorker.cs
  Src/WitsmlExplorer.Api/Workers/CopyLogWorker.cs
  Src/WitsmlExplorer.Api/Workers/CopyTrajectoryWorker.cs
  Src/WitsmlExplorer.Api/Workers/CreateLogWorker.cs
  Src/WitsmlExplorer.Api/Workers/CreateMessageWorker.cs
  Src/WitsmlExplorer.Api/Workers/CreateWellboreWorker.cs
  Src/WitsmlExplorer.Api/Workers/DeleteCurveValuesWorker.cs
  Src/WitsmlExplorer.Api/Workers/DeleteMnemonicsWorker.cs
  Src/WitsmlExplorer.Api/Workers/DeleteTrajectoryWorker.cs
  Src/WitsmlExplorer.Api/Workers/DeleteWellboreWorker.cs
  Src/WitsmlExplorer.Api/Workers/ModifyLogObjectWorker.cs
  Src/WitsmlExplorer.Api/Workers/ModifyWellboreWorker.cs
  Src/WitsmlExplorer.Api/Workers/RenameMnemonicWorker.cs
  Src/WitsmlExplorer.Api/Workers/TrimLogObjectWorker.cs
  Tests/WitsmlExplorer.IntegrationTests/Api/Workers/CopyLogWorkerTests.cs
  Tests/WitsmlExplorer.IntegrationTests/Witsml/AddToStore/LogObjectTests.cs
  Tests/WitsmlExplorer.IntegrationTests/Witsml/AddToStore/TrajectoryTests.cs
Labels: enhancement
