Repository equinor/witsml-explorer, pull requests merged in 2021-05, with the labels that each got.

#375 VirtualizedContentTable is not a generic implementation
  Src/WitsmlExplorer.Frontend/components/ContentViews/CurveValuesView.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/VirtualizedContentTable.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/tableParts.ts
Labels: bug

#374 Add batch update to front-end and connect to back-end
  Src/WitsmlExplorer.Frontend/components/ContentViews/WellsListView.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/__tests__/ContentTable.tests.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/ContentTable.tsx
  Src/WitsmlExplorer.Frontend/components/ContextMenus/WellContextMenu.tsx
  Src/WitsmlExplorer.Frontend/components/Modals/ModalParts.tsx
  Src/WitsmlExplorer.Frontend/components/Modals/UserCredentialsModal.tsx
  Src/WitsmlExplorer.Frontend/components/Modals/WellBatchUpdateModal.tsx
  Src/WitsmlExplorer.Frontend/components/Modals/WellPropertiesModal.tsx
  Src/WitsmlExplorer.Frontend/components/RefreshHandler.tsx
  Src/WitsmlExplorer.Frontend/contexts/modificationType.ts
  Src/WitsmlExplorer.Frontend/models/jobs/batchModifyWellJob.tsx
  Src/WitsmlExplorer.Frontend/services/jobService.tsx
Labels: enhancement

#388 Fix wrong name for elements in StnTrajMatrixCov and TrajectoryStation
  Src/Witsml/Data/WitsmlStnTrajMatrixCov.cs
  Src/Witsml/Data/WitsmlTrajectoryStation.cs
Labels: bug

#386 Selecting multiple rows with shift is unreliable in VirtualizedContentTable
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/VirtualizedContentTable.tsx
Labels: bug

#385 Deploy WE to IIS documentation
  CONTRIBUTING.md
  Src/WitsmlExplorer.Api/WitsmlExplorer.Api.csproj
Labels: documentation

#364 Enable environment variables to support deployment on distributed sys…
  Src/WitsmlExplorer.Frontend/.env.local
  Src/WitsmlExplorer.Frontend/components/AssetsLoader.ts
  Src/WitsmlExplorer.Frontend/components/GlobalStyles.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/AccessibleIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/CheckIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/CopyIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/DeleteIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/EditIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/FolderOpenIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/FormatLineSpacingIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/IsActiveIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/LaunchIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/NewIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/PasteIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/RefreshIcon.tsx
  Src/WitsmlExplorer.Frontend/components/Icons/SettingsIcon.tsx
  Src/WitsmlExplorer.Frontend/next.config.js
  Src/WitsmlExplorer.Frontend/package.json
  Src/WitsmlExplorer.Frontend/pages/index.tsx
  Src/WitsmlExplorer.Frontend/services/apiClient.tsx
  Src/WitsmlExplorer.Frontend/services/notificationService.ts
Labels: bug

#366 #173 Export log to .csv
  Src/WitsmlExplorer.Frontend/components/ContentViews/CurveValuesView.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/VirtualizedContentTable.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/tableParts.ts
  Src/WitsmlExplorer.Frontend/hooks/useExport.ts
  Src/WitsmlExplorer.Frontend/styles/material-eds.tsx
Labels: enhancement

#387 Add support for WitsmlRisks
  Src/Witsml/Data/WitsmlRisk.cs
  Src/Witsml/Data/WitsmlRisks.cs
  Src/Witsml/Query/RiskQueries.cs
Labels: enhancement

#405 Add isActive icon to LogCurveInfoListView
  Src/WitsmlExplorer.Frontend/components/ContentViews/LogCurveInfoListView.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/ContentTable.tsx
  Src/WitsmlExplorer.Frontend/components/ContentViews/table/tableParts.ts
  Src/WitsmlExplorer.Frontend/models/logData.ts
Labels: enhancement

#404 Added console application for querying witsml servers
  Src/Witsml/Extensions/WitsmlLogExtensions.cs
  Src/WitsmlExplorer.Api/Services/LogObjectService.cs
  Src/WitsmlExplorer.Console/.gitignore
  Src/WitsmlExplorer.Console/Extensions/StringExtensions.cs
  Src/WitsmlExplorer.Console/Injection/TypeRegistrar.cs
  Src/WitsmlExplorer.Console/Injection/TypeResolver.cs
  Src/WitsmlExplorer.Console/ListCommands/ListLogsCommand.cs
  Src/WitsmlExplorer.Console/ListCommands/ListWellboresCommand.cs
  Src/WitsmlExplorer.Console/Program.cs
  Src/WitsmlExplorer.Console/WitsmlClient/WitsmlClientProvider.cs
  Src/WitsmlExplorer.Console/WitsmlClient/WitsmlConfiguration.cs
  Src/WitsmlExplorer.Console/WitsmlExplorer.Console.csproj
  witsml-explorer.sln
Labels: enhancement
